// mockData.ts
export const mentors = [
    { id: 1, name: "John Doe", expertise: "Web Development" },
    { id: 2, name: "Jane Smith", expertise: "Data Science" },
    { id: 3, name: "Alice Johnson", expertise: "UI/UX Design" },
    { id: 4, name: "Michael Brown", expertise: "Software Engineering" },
    { id: 5, name: "Emily Davis", expertise: "Graphic Design" },
    { id: 6, name: "Chris Wilson", expertise: "Cybersecurity" },
    { id: 7, name: "Sarah Miller", expertise: "Digital Marketing" },
    { id: 8, name: "David Anderson", expertise: "Mobile App Development" },
    { id: 9, name: "Laura Thomas", expertise: "Cloud Computing" },
    { id: 10, name: "James Jackson", expertise: "SEO Specialist" },
    { id: 11, name: "Sophia White", expertise: "Data Analysis" },
    { id: 12, name: "Liam Harris", expertise: "Blockchain Technology" },
    { id: 13, name: "Olivia Martinez", expertise: "Content Writing" },
    { id: 14, name: "Benjamin Robinson", expertise: "Machine Learning" },
    { id: 15, name: "Mia Clark", expertise: "Network Administration" },
    { id: 16, name: "Elijah Lewis", expertise: "Database Management" },
    { id: 17, name: "Isabella Walker", expertise: "Game Development" },
    { id: 18, name: "Lucas Hall", expertise: "DevOps" },
    { id: 19, name: "Charlotte Allen", expertise: "Business Analysis" },
    { id: 20, name: "Amelia Young", expertise: "Artificial Intelligence" },
    { id: 21, name: "Alexander King", expertise: "Full Stack Development" },
    { id: 22, name: "Evelyn Wright", expertise: "Software Testing" },
    { id: 23, name: "Daniel Scott", expertise: "IT Support" },
    { id: 24, name: "Grace Green", expertise: "Project Management" },
    { id: 25, name: "Henry Adams", expertise: "E-commerce" },
    { id: 26, name: "Ella Baker", expertise: "User Research" },
    { id: 27, name: "Matthew Gonzalez", expertise: "Web Security" },
    { id: 28, name: "Ava Nelson", expertise: "Salesforce Development" },
    { id: 29, name: "Joseph Carter", expertise: "AR/VR Development" },
    { id: 30, name: "Sofia Mitchell", expertise: "Technical Writing" },
    { id: 31, name: "Samuel Perez", expertise: "Telecommunications" },
    { id: 32, name: "Scarlett Roberts", expertise: "Front End Development" },
    { id: 33, name: "Jack Turner", expertise: "API Development" },
    { id: 34, name: "Victoria Phillips", expertise: "Risk Management" },
    { id: 35, name: "David Campbell", expertise: "Quality Assurance" },
    { id: 36, name: "Luna Parker", expertise: "Social Media Management" },
    { id: 37, name: "Ryan Evans", expertise: "Web Accessibility" },
    { id: 38, name: "Chloe Edwards", expertise: "Data Visualization" },
    { id: 39, name: "William Collins", expertise: "Artificial Neural Networks" },
    { id: 40, name: "Zoe Stewart", expertise: "CRM Solutions" },
    { id: 41, name: "Matthew Sanchez", expertise: "User Interface Testing" },
    { id: 42, name: "Hazel Morris", expertise: "Agile Methodology" },
    { id: 43, name: "Ethan Reed", expertise: "Business Intelligence" },
    { id: 44, name: "Emily Cooper", expertise: "Mobile Game Development" },
    { id: 45, name: "Charlotte Bailey", expertise: "Web Analytics" },
    { id: 46, name: "Mason Rivera", expertise: "E-learning Solutions" },
    { id: 47, name: "Aria Richardson", expertise: "Information Security" },
    { id: 48, name: "Jackson Wood", expertise: "Content Management Systems" },
    { id: 49, name: "Aiden Bell", expertise: "Enterprise Resource Planning" },
    { id: 50, name: "Penelope Murphy", expertise: "Web Hosting" },
    { id: 51, name: "Levi Cooper", expertise: "Cloud Solutions Architect" },
    { id: 52, name: "Lily Ward", expertise: "IT Governance" },
    { id: 53, name: "Henry Cox", expertise: "Health Informatics" },
    { id: 54, name: "Nora Brooks", expertise: "Software Architecture" },
    { id: 55, name: "Eliana Sanders", expertise: "UX Research" },
    { id: 56, name: "Wyatt Price", expertise: "Network Security" },
    { id: 57, name: "Anna Bennett", expertise: "Technical Support" },
    { id: 58, name: "Michael Foster", expertise: "Integration Solutions" },
    { id: 59, name: "Aubrey Powell", expertise: "Mobile Security" },
    { id: 60, name: "Lucas Perry", expertise: "Data Privacy" },
    { id: 61, name: "Madison Long", expertise: "Web Performance" },
    { id: 62, name: "Jaxon Sanders", expertise: "Cloud Security" },
    { id: 63, name: "Chloe Hayes", expertise: "IT Compliance" },
    { id: 64, name: "Oliver Reed", expertise: "Software Documentation" },
];
